[package]
name = "transFile"
version = "0.0.2"
authors = ["YOYOJ"]
description = "一个简单易用的文件转换工具，支持多种图片格式转换"
edition = "2024"

[dependencies]
image = "0.24"
icns = "0.3.1"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive", "cargo"] }
ico = "0.4.0"
webp = "0.3.0"
