[package]
name = "upload"
version = "0.1.0"
edition = "2024"

[dependencies]
aliyun-oss-rust-sdk = "0.2.1"
async-trait = "0.1.88"
chrono = "0.4.41"
mime_guess = "2.0.5"
qiniu-sdk = "0.2.4"
qiniu-upload-token = "0.2.4"
reqwest = { version = "0.12.22", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.46.1", features = ["full"] }

[dev-dependencies]
dotenv = "0.15.0"
